/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import gestor.Conexion;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author carri
 */
public class IntValidarActivo extends javax.swing.JFrame {

	Conexion conexion;
	JTable tablaActivos;
	int posicion, idProceso;
	IntDetalleProceso origen;

	/**
	 * Creates new form IntValidarActivo
	 */
	public IntValidarActivo(JTable tablaActivos, IntDetalleProceso origen, int idProceso, int posicion) {
		initComponents();
		this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
		this.origen = origen;
		this.conexion = new Conexion();
		this.idProceso = idProceso;
		this.tablaActivos = tablaActivos;
		this.posicion = posicion;
		this.jTxaObservacion.setEditable(false);
		this.jRbtCorrecto.setSelected(true);
		ButtonGroup grupo = new ButtonGroup();
		grupo.add(jRbtCorrecto);
		grupo.add(jRbtObservacion);

		cargarDatos();
	}

	public void cargarDatos() {
		String idActivo = (String) tablaActivos.getValueAt(posicion, 0);
		String cedula = (String) tablaActivos.getValueAt(posicion, 4);
		jLabel1.setText(idActivo);
		jLabel2.setText(cedula);
	}

	public void validarActivo() {
		cargarDatos();
		String idActivo = (String) tablaActivos.getValueAt(posicion, 0);
		String estadoActivo;
		String observacionActivo;
		if (jRbtCorrecto.isSelected()) {
			estadoActivo = "CORRECTO";
			observacionActivo = "";
		} else {
			estadoActivo = "OBSERVACION";
			observacionActivo = jTxaObservacion.getText();
		}
		try {
			this.conexion.validarActivo(idActivo, idProceso, estadoActivo, observacionActivo);
		} catch (Exception ex) {
			Logger.getLogger(IntValidarActivo.class.getName()).log(Level.SEVERE, null, ex);
		}

	}

	public void validarYSiguiente() {
		System.out.println(posicion);
		validarActivo();
		this.posicion += 1;
		if (this.posicion == tablaActivos.getRowCount()) {
			JOptionPane.showMessageDialog(null, "Ha terminado el proceso de validacion!");
			this.origen.actualizarVentana();
			this.dispose();
		} else {
			cargarDatos();
			this.jRbtCorrecto.setSelected(true);
			this.jTxaObservacion.setText("");
			this.jTxaObservacion.setEditable(false);
		}
	}

	public IntValidarActivo() {
		initComponents();
		this.jRbtCorrecto.setSelected(true);
		this.jTxaObservacion.setEditable(false);
		ButtonGroup grupo = new ButtonGroup();
		grupo.add(jRbtCorrecto);
		grupo.add(jRbtObservacion);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButtonGroup = new javax.swing.ButtonGroup();
        jRbtCorrecto = new javax.swing.JRadioButton();
        jRbtObservacion = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxaObservacion = new javax.swing.JTextArea();
        jBtnCancelar = new javax.swing.JButton();
        jBtnGuardar = new javax.swing.JButton();
        jBtnSiguiente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRbtCorrecto.setText("Correcto");
        jRbtCorrecto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRbtCorrectoItemStateChanged(evt);
            }
        });
        jRbtCorrecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRbtCorrectoMouseClicked(evt);
            }
        });
        jRbtCorrecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbtCorrectoActionPerformed(evt);
            }
        });

        jRbtObservacion.setText("Observacion");
        jRbtObservacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRbtObservacionMouseClicked(evt);
            }
        });

        jTxaObservacion.setColumns(20);
        jTxaObservacion.setRows(5);
        jScrollPane1.setViewportView(jTxaObservacion);

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnGuardar.setText("Guardar y Salir");
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });

        jBtnSiguiente.setText("Guardar y Siguiente");
        jBtnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSiguienteActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Activo");

        jLabel2.setText("Cedula Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jRbtCorrecto)
                                .addGap(63, 63, 63)
                                .addComponent(jRbtObservacion))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnSiguiente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRbtCorrecto)
                    .addComponent(jRbtObservacion))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnGuardar)
                    .addComponent(jBtnSiguiente))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
		// TODO add your handling code here:
		this.validarActivo();
		this.origen.actualizarVentana();
		this.dispose();
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void jBtnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSiguienteActionPerformed
		// TODO add your handling code here
		this.validarYSiguiente();
    }//GEN-LAST:event_jBtnSiguienteActionPerformed

    private void jRbtCorrectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbtCorrectoActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jRbtCorrectoActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
		// TODO add your handling code here:
		this.origen.actualizarVentana();
		this.dispose();
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jRbtCorrectoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRbtCorrectoItemStateChanged
    }//GEN-LAST:event_jRbtCorrectoItemStateChanged

    private void jRbtCorrectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRbtCorrectoMouseClicked
		// TODO add your handling code here:
		this.jTxaObservacion.setEditable(false);
		this.jTxaObservacion.setText("");
    }//GEN-LAST:event_jRbtCorrectoMouseClicked

    private void jRbtObservacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRbtObservacionMouseClicked
		// TODO add your handling code here:
		jTxaObservacion.setEditable(true);
    }//GEN-LAST:event_jRbtObservacionMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(IntValidarActivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(IntValidarActivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(IntValidarActivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(IntValidarActivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new IntValidarActivo().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRbtCorrecto;
    private javax.swing.JRadioButton jRbtObservacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxaObservacion;
    private javax.swing.ButtonGroup radioButtonGroup;
    // End of variables declaration//GEN-END:variables
}
