/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import com.itextpdf.text.log.Logger;
import componentes.Render;
import entidades.Activo;
import entidades.Proceso;
import gestor.Conexion;
import gestor.GeneradorPDF;
import gestor.Gestor;
import java.awt.Color;
import java.lang.System.Logger.Level;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carri
 */
public class pruebas extends javax.swing.JFrame {

	Conexion conexion;
	DefaultTableModel modeloTablaActivos;
	Proceso proceso;

	/**
	 * Creates new form pruebas
	 */
	public pruebas() {
		initComponents();
		String idProceso = "18";
		this.tablaUsuariosProceso1.cargarTabla(idProceso);
		this.proceso = Gestor._getGestor().getProceso(idProceso);
		cargarTablaActivos();

	}

	private void cargarTablaActivos() {
		jTblActivosProceso.setDefaultRenderer(Object.class, new Render());
		String[] titulos = {"ID ACTIVO", "ID OBJETO", "NOMBRE", "DESCRIPCION", "CEDULA USUARIO",
			"NOMBRE USUARIO", "APELLIDO USUARIO", "REVISADO", "ESTADO REVISION", "OBSERVACION REVISION", ""};
		this.modeloTablaActivos = new DefaultTableModel(null, titulos) {
			@Override
			public boolean isCellEditable(int row, int column) {
				return false;
			}
		};
		try {
			for (Activo activo : this.proceso.getActivos()) {
				JButton btnValidar = new JButton("Validar");
				btnValidar.setBackground(Color.green);
				btnValidar.setForeground(Color.white);
				String revision = "";
				System.out.println(activo.toString());
				if (activo.getRevisionActivo() == 1) {
					revision = "REVISADO";
				}
				Object[] datos = {activo.getIdPertinencia(),
					activo.getIdActivo(), activo.getNombreActivo(),
					activo.getDescripcionActivo(),
					activo.getUsuario().getCedula(),
					activo.getUsuario().getNombre(),
					activo.getUsuario().getApellido(),
					revision,
					activo.getEstadoRevisionActivo(),
					activo.getObservacionRevision(),
					btnValidar
				};
				modeloTablaActivos.addRow(datos);
			}
			jTblActivosProceso.setModel(modeloTablaActivos);
			jTblActivosProceso.setRowHeight(20);
		} catch (Exception ex) {
			JOptionPane.showMessageDialog(null, "Error: No se ha podido comunicar con el servidor");
		}
	}
	private void generarPdf() {
		// TODO add your handling code here:
		JFileChooser jFlcDestinoPdf = new JFileChooser();
		jFlcDestinoPdf.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		int opcion = jFlcDestinoPdf.showSaveDialog(this);
		if (opcion == JFileChooser.APPROVE_OPTION) {
			try {
				String path = jFlcDestinoPdf.getSelectedFile().getAbsolutePath() + "\\";
				System.out.println(path);
				GeneradorPDF gpdf = new GeneradorPDF();
				//gpdf.generarPdf(jTblActivosProceso, path, proceso.getNombre());
			} catch (Exception ex) {
				JOptionPane.showMessageDialog(null, ex);
			}
		}
	}


	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuariosProceso1 = new componentes.TablaUsuariosProceso();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTblActivosProceso = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaUsuariosProceso1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaUsuariosProceso1);

        jTblActivosProceso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTblActivosProceso);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
		generarPdf();
    }//GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new pruebas().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTblActivosProceso;
    private componentes.TablaUsuariosProceso tablaUsuariosProceso1;
    // End of variables declaration//GEN-END:variables
}
