/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentes;

import com.itextpdf.text.log.Level;
import entidades.Proceso;
import gestor.GeneradorPDF;
import gestor.Gestor;
import java.awt.Component;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author carri
 */
public class PnlDetalleProceso extends javax.swing.JPanel {

	Proceso proceso;
	String idProceso;
	JTabbedPane tabbedPane; 

	/**
	 * Creates new form PnlDetalleProceso
	 */
	public PnlDetalleProceso(String idProceso) {
		initComponents();
		this.idProceso = idProceso;
		this.proceso = Gestor._getGestor().getProceso(idProceso);
		cargarDatos();
		this.tablaUsuariosProceso1.cargarTabla(idProceso);
		this.tablaUsuariosProceso1.setTablaActivos(tablaActivosProceso1);
		this.tablaActivosProceso1.cargarTabla(idProceso);
		this.tablaActivosProceso1.setPanel(this); 

	}

	public void setProceso(Proceso proceso) {
		this.proceso = proceso;
		cargarDatos();
	}

	public void cargarDatos() {
		jLblIdProceso.setText(idProceso);
		jLblNombreProceso.setText(proceso.getNombre());
		jLblFechaProceso.setText(proceso.getFecha());
		jLblEstado.setText(proceso.getEstado());
	}

	public String getNombreProceso(){
		return this.proceso.getNombre(); 
	}

	public void setTabbedPane(JTabbedPane tabbedPane){
		this.tabbedPane = tabbedPane; 
	}

	private void generarPdf() {
		// TODO add your handling code here:
		JFileChooser jFlcDestinoPdf = new JFileChooser();
		jFlcDestinoPdf.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		int opcion = jFlcDestinoPdf.showSaveDialog(this);
		if (opcion == JFileChooser.APPROVE_OPTION) {
			try {
				String path = jFlcDestinoPdf.getSelectedFile().getAbsolutePath() + "\\";
				System.out.println(path);
				GeneradorPDF gpdf = new GeneradorPDF();
				System.out.println("Crea el Generados");
				gpdf.generarPdf(this.tablaActivosProceso1, path, proceso.getNombre());
			} catch (Exception ex) {
				JOptionPane.showMessageDialog(null, "Ocurrio un error al crear su pdf!");
			}
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLblEstado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaUsuariosProceso1 = new componentes.TablaUsuariosProceso();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaActivosProceso1 = new componentes.TablaActivosProceso();
        jLblIdProceso = new javax.swing.JLabel();
        jLblNombreProceso = new javax.swing.JLabel();
        jBtnLimpiar = new javax.swing.JButton();
        jLblFechaProceso = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jButton1.setText("Generar PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("ESTADO:");

        jLblEstado.setText("CREADO");

        jLabel1.setText("ID PROCESO:");

        tablaUsuariosProceso1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaUsuariosProceso1);

        jLabel2.setText("NOMBRE PROCESO:");

        jLabel3.setText("FECHA DE CREACION DEL PROCESO: ");

        tablaActivosProceso1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaActivosProceso1);

        jLblIdProceso.setText("ID");

        jLblNombreProceso.setText("NOMBRE");

        jBtnLimpiar.setText("Limpiar Selección");
        jBtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimpiarActionPerformed(evt);
            }
        });

        jLblFechaProceso.setText("FECHA");

        jLabel4.setText("USUARIOS REGISTRADOS EN EL PROCESO");

        jLabel5.setText("ACTIVOS DEL PROCESO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblNombreProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblFechaProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblIdProceso)
                                .addGap(66, 66, 66)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLblEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(22, 22, 22))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jBtnLimpiar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLblIdProceso)
                    .addComponent(jLabel6)
                    .addComponent(jLblEstado)
                    .addComponent(jButton1))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLblNombreProceso))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLblFechaProceso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		generarPdf();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimpiarActionPerformed
		// TODO add your handling code here:
		this.tablaActivosProceso1.getSelectionModel().clearSelection();
		this.tablaUsuariosProceso1.getSelectionModel().clearSelection();
    }//GEN-LAST:event_jBtnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLimpiar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLblEstado;
    private javax.swing.JLabel jLblFechaProceso;
    private javax.swing.JLabel jLblIdProceso;
    private javax.swing.JLabel jLblNombreProceso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private componentes.TablaActivosProceso tablaActivosProceso1;
    private componentes.TablaUsuariosProceso tablaUsuariosProceso1;
    // End of variables declaration//GEN-END:variables
}
